name: qhse
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  firebase_core: ^3.1.1
  connectivity: ^3.0.6
  image_picker: ^1.1.2
  firebase_auth: ^5.1.1
  firebase_storage: ^12.1.0
  firebase_database: ^11.0.2
  cached_network_image: ^3.3.1
  logger: ^2.3.0
  photo_view: ^0.15.0
  flutter_file_dialog: ^3.0.2
  flutter_colorpicker: ^1.1.0
  overlay_support: ^2.1.0
  multi_select_flutter: ^4.1.3
  file_picker: ^8.0.6
  syncfusion_flutter_datagrid: ^26.1.41
  shared_preferences: ^2.2.3
  path: ^1.9.0
  screenshot: ^3.0.0
  flutter_typeahead: ^5.2.0
  geolocator: ^12.0.0
  intl: ^0.19.0
  pdf: ^3.11.1
  printing: ^5.13.1
  permission_handler: ^11.3.1



dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/


  fonts:
    - family: LEMONMILK
      fonts:
        - asset: fonts/LEMONMILK-Bold.otf

  
  
