// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCZjvX6hHnxvlcXs_aamjTJQOC4BauQ_dA',
    appId: '1:935770728387:web:22564305b555b48d43bf76',
    messagingSenderId: '935770728387',
    projectId: 'qhse-49ff4',
    authDomain: 'qhse-49ff4.firebaseapp.com',
    storageBucket: 'qhse-49ff4.appspot.com',
    measurementId: 'G-30DM8FYYS3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBlo-w8zCYoIK7F-hPQNzidKg1Er6gGRzY',
    appId: '1:935770728387:android:b98cb2a11dbd7f5b43bf76',
    messagingSenderId: '935770728387',
    projectId: 'qhse-49ff4',
    storageBucket: 'qhse-49ff4.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAy1WzBjnbR01WwmWZSoUew2W8RdbzGeOs',
    appId: '1:935770728387:ios:aa92bfe573c6f77c43bf76',
    messagingSenderId: '935770728387',
    projectId: 'qhse-49ff4',
    storageBucket: 'qhse-49ff4.appspot.com',
    iosBundleId: 'com.example.qhse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAy1WzBjnbR01WwmWZSoUew2W8RdbzGeOs',
    appId: '1:935770728387:ios:aa92bfe573c6f77c43bf76',
    messagingSenderId: '935770728387',
    projectId: 'qhse-49ff4',
    storageBucket: 'qhse-49ff4.appspot.com',
    iosBundleId: 'com.example.qhse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCZjvX6hHnxvlcXs_aamjTJQOC4BauQ_dA',
    appId: '1:935770728387:web:c8a76049614e8faa43bf76',
    messagingSenderId: '935770728387',
    projectId: 'qhse-49ff4',
    authDomain: 'qhse-49ff4.firebaseapp.com',
    storageBucket: 'qhse-49ff4.appspot.com',
    measurementId: 'G-PVEW15ZX4D',
  );
}
